---
- name: Install pip
  apt: name=python3-pip state=present
- name: install docker-py
  pip: name=docker-py
- name: Install docker.io
  apt: name=docker.io
- name: Ensure service is enabled
  command: systemctl restart docker
- name: copy custom files
  copy: 
   src: '{{item}}'
   dest: './{{item}}'
  loop:
          - trigger-job.sh
          - trigger-job.groovy
          - sample-maven-job_config.xml
          - install-plugins.sh
          - executors.groovy
          - default-user.groovy
          - credentials.xml
          - create-freestyle.groovy
          - create-credential.groovy
          - Dockerfile
          - config.xml
- name: Build Docker image from Dockerfile
  docker_image:
            name: jenkins_custom
            source: build
            build:
              path: ./
#            state: present
#          dockerfile: Dockerfile
- name: Running the container
  docker_container:
            name: jenkins_ansi_anil
            image: jenkins_custom:latest
            ports:
                    - 8881:8080
- name: Check if container is running
  shell: docker ps
